import type { Metadata } from "next"

import "./globals.css"
import Header from "@/components/header"
import { roboto } from "@/lib/fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
