import { Website } from "./types/website.type"

export const mockWebsites: Website[] = [
  {
    id: "1",
    url: "https://techcrunch.com",
    name: "TechCrunch",
    category: "Technology",
    keywords: ["startups", "tech", "gadgets"],
    trafficAverage: "10M",
    language: "English",
    geoReach: ["United States", "Canada", "United Kingdom"],
  },
  {
    id: "2",
    url: "https://foodnetwork.com",
    name: "Food Network",
    category: "Food & Cooking",
    keywords: ["recipes", "cooking", "chefs"],
    trafficAverage: "8M",
    language: "English",
    geoReach: ["United States", "Australia", "United Kingdom"],
  },
  {
    id: "3",
    url: "https://lemonde.fr",
    name: "Le Monde",
    category: "News",
    keywords: ["politics", "international", "economy"],
    trafficAverage: "5M",
    language: "French",
    geoReach: ["France", "Belgium", "Switzerland"],
  },
  {
    id: "4",
    url: "https://animenewsnetwork.com",
    name: "Anime News Network",
    category: "Entertainment",
    keywords: ["anime", "manga", "reviews"],
    trafficAverage: "2M",
    language: "English",
    geoReach: ["United States", "Japan", "Canada"],
  },
  {
    id: "5",
    url: "https://cntraveler.com",
    name: "Condé Nast Traveler",
    category: "Travel",
    keywords: ["destinations", "hotels", "travel tips"],
    trafficAverage: "3M",
    language: "English",
    geoReach: ["United States", "United Kingdom", "Australia"],
  },
]
