const mockWebsites = [
  {
    id: "1",
    name: "Tech Innovators",
    url: "https://www.techinnovators.com",
    category: "Technology",
    trafficVolume: "100k+",
    contactEmail: "contact@techinnovators.com",
  },
  {
    id: "2",
    name: "Health Matters",
    url: "https://www.healthmatters.com",
    category: "Health",
    trafficVolume: "50k-100k",
    contactEmail: "info@healthmatters.com",
  },
  {
    id: "3",
    name: "Finance Daily",
    url: "https://www.financedaily.com",
    category: "Finance",
    trafficVolume: "10k-50k",
    contactEmail: "support@financedaily.com",
  },
  {
    id: "4",
    name: "Fashion Trends",
    url: "https://www.fashiontrends.com",
    category: "Fashion",
    trafficVolume: "50k-100k",
    contactEmail: "hello@fashiontrends.com",
  },
  {
    id: "5",
    name: "Gourmet Kitchen",
    url: "https://www.gourmetkitchen.com",
    category: "Food & Drink",
    trafficVolume: "10k-50k",
    contactEmail: "contact@gourmetkitchen.com",
  },
  {
    id: "6",
    name: "Travel Explorer",
    url: "https://www.travelexplorer.com",
    category: "Travel",
    trafficVolume: "100k+",
    contactEmail: "inquiries@travelexplorer.com",
  },
  {
    id: "7",
    name: "Gaming Hub",
    url: "https://www.gaminghub.com",
    category: "Entertainment",
    trafficVolume: "50k-100k",
    contactEmail: "contact@gaminghub.com",
  },
  {
    id: "8",
    name: "Eco Living",
    url: "https://www.ecoliving.com",
    category: "Environment",
    trafficVolume: "10k-50k",
    contactEmail: "info@ecoliving.com",
  },
  {
    id: "9",
    name: "Sports Central",
    url: "https://www.sportscentral.com",
    category: "Sports",
    trafficVolume: "100k+",
    contactEmail: "contact@sportscentral.com",
  },
  {
    id: "10",
    name: "Artistic Expressions",
    url: "https://www.artisticexpressions.com",
    category: "Art & Culture",
    trafficVolume: "<10k",
    contactEmail: "support@artisticexpressions.com",
  },
]

export default mockWebsites
